### PR TITLE
Fix code chunk parsing

### PR DESCRIPTION
**Pull request by Altai-man**
Fixes https://github.com/retupmoca/p6-markdown/issues/23
cast @JJ

### CODE REVIEW

**Comment by JJ** [comment]
There seems to be a problem with the tests. Can you please check them?

**Comment by Altai-man** [comment]
Ah, indeed. I have only checked `parse.t` with new tests... Okay, will be fixed, thanks!

**Comment by JJ** [comment]
Thanks!

One of the tests, BTW, is always failing; there's some issue with moar
2017.6 and one of the upstream dependencies, but I'm afraid I didn't have
time to check it.

**Comment by Altai-man** [comment]
Updated travis file too, `06` is kind of old now, I guess, so `09` looks better.

**Pull request merged**
